---
http_interactions:
- request:
    method: post
    uri: https://core.myedools.com/schools/wizard
    body:
      encoding: ASCII-8BIT
      string: "------RubyFormBoundarympMi8bVwW2IJqKCL\r\nContent-Disposition: form-data;
        name=\"school[name]\"\r\n\r\nTest\r\n------RubyFormBoundarympMi8bVwW2IJqKCL\r\nContent-Disposition:
        form-data; name=\"school[email]\"\r\n\r\ntest@test.com\r\n------RubyFormBoundarympMi8bVwW2IJqKCL\r\nContent-Disposition:
        form-data; name=\"school[password]\"\r\n\r\n12345678\r\n------RubyFormBoundarympMi8bVwW2IJqKCL--\r\n"
    headers:
      Accept:
      - application/vnd.edools.core.v1+json
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - rest-client/2.0.2 (darwin16.7.0 x86_64) ruby/2.4.1p111
      Authorization:
      - Token token="e20c3d8a4c6f1c3da2a90704e87b6291:9a960117fe097dbf1d2eb8a5b30c3185"
      Content-Length:
      - '363'
      Content-Type:
      - multipart/form-data; boundary=----RubyFormBoundarympMi8bVwW2IJqKCL
      Host:
      - core.myedools.com
  response:
    status:
      code: 201
      message: Created
    headers:
      Cache-Control:
      - max-age=0, private, must-revalidate
      Content-Security-Policy-Report-Only:
      - default-src https://* 'self'; connect-src https://* 'self'; font-src https://*
        'self'; frame-src https://* 'self'; img-src https://* 'self' data:; media-src
        https://* 'self'; object-src https://* 'self'; script-src https://* 'self';
        style-src https://* 'self'; report-uri https://core.edools.com/uri-directive;
      Content-Type:
      - application/vnd.edools.core.v1+json; charset=utf-8
      Date:
      - Wed, 04 Oct 2017 00:47:35 GMT
      Etag:
      - W/"e8a2b7ab93c0cf5720f634d9f0534b13"
      Location:
      - https://core.myedools.com/schools/1302
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 201 Created
      Strict-Transport-Security:
      - max-age=631152000; includeSubdomains
      Vary:
      - Origin
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Frame-Options:
      - DENY
      X-Permitted-Cross-Domain-Policies:
      - none
      X-Request-Id:
      - ba2c5d23-3e7d-4aa5-b394-4a6bdaddac86
      X-Runtime:
      - '1.711511'
      X-Xss-Protection:
      - 1; mode=block
      Content-Length:
      - '306'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"school":{"id":1302,"subdomain":"test-846e","name":"Test"},"library":{"id":1302},"organization":{"id":1296,"name":"Test"},"admin":{"id":591594,"full_name":"Test","email":"test@test.com","credentials":"542bfc5c9183f2a26eb0de4d396da660:404f82e888cf63542376bfdc92c2d2b1","role_id":17073},"forum":{"id":1302}}'
    http_version: 
  recorded_at: Wed, 04 Oct 2017 00:47:35 GMT
recorded_with: VCR 3.0.3
