---
http_interactions:
- request:
    method: post
    uri: https://core.myedools.info/schools/wizard
    body:
      encoding: ASCII-8BIT
      string: "------RubyFormBoundary3Wq6CzwATW9iVa6t\r\nContent-Disposition: form-data;
        name=\"school[name]\"\r\n\r\nTest\r\n------RubyFormBoundary3Wq6CzwATW9iVa6t\r\nContent-Disposition:
        form-data; name=\"school[email]\"\r\n\r\ntest@test.com\r\n------RubyFormBoundary3Wq6CzwATW9iVa6t\r\nContent-Disposition:
        form-data; name=\"school[password]\"\r\n\r\n12345678\r\n------RubyFormBoundary3Wq6CzwATW9iVa6t--\r\n"
    headers:
      Accept:
      - application/vnd.edools.core.v1+json
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - rest-client/2.0.2 (darwin16.7.0 x86_64) ruby/2.4.1p111
      Authorization:
      - Token token="e20c3d8a4c6f1c3da2a90704e87b6291:9a960117fe097dbf1d2eb8a5b30c3185"
      Content-Length:
      - '363'
      Content-Type:
      - multipart/form-data; boundary=----RubyFormBoundary3Wq6CzwATW9iVa6t
      Host:
      - core.myedools.info
  response:
    status:
      code: 201
      message: Created
    headers:
      Cache-Control:
      - max-age=0, private, must-revalidate
      Content-Security-Policy-Report-Only:
      - default-src https://* 'self'; connect-src https://* 'self'; font-src https://*
        'self'; frame-src https://* 'self'; img-src https://* 'self' data:; media-src
        https://* 'self'; object-src https://* 'self'; script-src https://* 'self';
        style-src https://* 'self'; report-uri https://core.edools.com/uri-directive;
      Content-Type:
      - application/vnd.edools.core.v1+json; charset=utf-8
      Date:
      - Wed, 04 Oct 2017 00:39:55 GMT
      Etag:
      - W/"820936e5bf961f3e275e8269923ca14a"
      Location:
      - https://core.myedools.info/schools/1278
      Server:
      - nginx/1.4.6 (Ubuntu)
      Status:
      - 201 Created
      Strict-Transport-Security:
      - max-age=631152000; includeSubdomains
      Vary:
      - Origin
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Frame-Options:
      - DENY
      X-Permitted-Cross-Domain-Policies:
      - none
      X-Request-Id:
      - d766fc16-2c41-4f64-ba0a-71d22b001430
      X-Runtime:
      - '1.731902'
      X-Xss-Protection:
      - 1; mode=block
      Content-Length:
      - '306'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"school":{"id":1278,"subdomain":"test-a739","name":"Test"},"library":{"id":1278},"organization":{"id":1272,"name":"Test"},"admin":{"id":591545,"full_name":"Test","email":"test@test.com","credentials":"210f427ece0b820e11d02a2775348fcd:6ea31ff568f8c29361f1d422ec55f285","role_id":16785},"forum":{"id":1278}}'
    http_version: 
  recorded_at: Wed, 04 Oct 2017 00:39:55 GMT
recorded_with: VCR 3.0.3
